### PR TITLE
fix/update join

### PR DESCRIPTION
**Pull request by amychen1776**
This fixes the join which calls in one of the columns that is being lowercased in Snowflake.

### CODE REVIEW

**Comment by drewbanin** [comment]
I think we need to change `medium` to `referrer` medium too here: https://github.com/fishtown-analytics/heap/commit/96307cb259ce317c99c2a3f442436b545a74f770

**Comment by amychen1776** [comment]
> I think we need to change `medium` to `referrer_medium` too here: [96307cb](https://github.com/fishtown-analytics/heap/commit/96307cb259ce317c99c2a3f442436b545a74f770)

Yup, just fixed!

**Comment by drewbanin** [comment]
Great, thanks! Ok - last thing - can you try running this package locally to ensure that the fixes here work in practice? Just a working run of the `heap_sessions_xf ` model would be awesome

**Comment by amychen1776** [comment]
> Great, thanks! Ok - last thing - can you try running this package locally to ensure that the fixes here work in practice? Just a working run of the `heap_sessions_xf ` model would be awesome

I would love to but unfortunately this happens to be the only model we don't use from the heap package in my project. That's why it was missed the first time. This does match how I fixed my project's version though.

**Comment by amychen1776** [comment]
> ship it.
> 
> can you cut a new version too?

Yup!

**Pull request merged**
